#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaaclifeCal.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BAACLIFECAL")]
	public partial class dbAccountDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertgender(gender instance);
    partial void Updategender(gender instance);
    partial void Deletegender(gender instance);
    partial void Insertpaytype(paytype instance);
    partial void Updatepaytype(paytype instance);
    partial void Deletepaytype(paytype instance);
    partial void InsertsavingAmount(savingAmount instance);
    partial void UpdatesavingAmount(savingAmount instance);
    partial void DeletesavingAmount(savingAmount instance);
    partial void InsertbenefitType(benefitType instance);
    partial void UpdatebenefitType(benefitType instance);
    partial void DeletebenefitType(benefitType instance);
    #endregion
		
		public dbAccountDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BAACLIFECALConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbAccountDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbAccountDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbAccountDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbAccountDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<gender> genders
		{
			get
			{
				return this.GetTable<gender>();
			}
		}
		
		public System.Data.Linq.Table<paytype> paytypes
		{
			get
			{
				return this.GetTable<paytype>();
			}
		}
		
		public System.Data.Linq.Table<savingAmount> savingAmounts
		{
			get
			{
				return this.GetTable<savingAmount>();
			}
		}
		
		public System.Data.Linq.Table<benefitType> benefitTypes
		{
			get
			{
				return this.GetTable<benefitType>();
			}
		}
		
		public System.Data.Linq.Table<paidUp> paidUps
		{
			get
			{
				return this.GetTable<paidUp>();
			}
		}
		
		public System.Data.Linq.Table<surrender> surrenders
		{
			get
			{
				return this.GetTable<surrender>();
			}
		}
		
		public System.Data.Linq.Table<fundAmt> fundAmts
		{
			get
			{
				return this.GetTable<fundAmt>();
			}
		}
		
		public System.Data.Linq.Table<Class1> Class1s
		{
			get
			{
				return this.GetTable<Class1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gender")]
	public partial class gender : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _genderCode;
		
		private string _genderDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngenderCodeChanging(string value);
    partial void OngenderCodeChanged();
    partial void OngenderDetailChanging(string value);
    partial void OngenderDetailChanged();
    #endregion
		
		public gender()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genderCode", DbType="NVarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string genderCode
		{
			get
			{
				return this._genderCode;
			}
			set
			{
				if ((this._genderCode != value))
				{
					this.OngenderCodeChanging(value);
					this.SendPropertyChanging();
					this._genderCode = value;
					this.SendPropertyChanged("genderCode");
					this.OngenderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genderDetail", DbType="NVarChar(50)")]
		public string genderDetail
		{
			get
			{
				return this._genderDetail;
			}
			set
			{
				if ((this._genderDetail != value))
				{
					this.OngenderDetailChanging(value);
					this.SendPropertyChanging();
					this._genderDetail = value;
					this.SendPropertyChanged("genderDetail");
					this.OngenderDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paytype")]
	public partial class paytype : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _paytypeCode;
		
		private string _paytypeDetail;
		
		private System.Nullable<int> _discount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpaytypeCodeChanging(string value);
    partial void OnpaytypeCodeChanged();
    partial void OnpaytypeDetailChanging(string value);
    partial void OnpaytypeDetailChanged();
    partial void OndiscountChanging(System.Nullable<int> value);
    partial void OndiscountChanged();
    #endregion
		
		public paytype()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paytypeCode", DbType="NVarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string paytypeCode
		{
			get
			{
				return this._paytypeCode;
			}
			set
			{
				if ((this._paytypeCode != value))
				{
					this.OnpaytypeCodeChanging(value);
					this.SendPropertyChanging();
					this._paytypeCode = value;
					this.SendPropertyChanged("paytypeCode");
					this.OnpaytypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paytypeDetail", DbType="NVarChar(50)")]
		public string paytypeDetail
		{
			get
			{
				return this._paytypeDetail;
			}
			set
			{
				if ((this._paytypeDetail != value))
				{
					this.OnpaytypeDetailChanging(value);
					this.SendPropertyChanging();
					this._paytypeDetail = value;
					this.SendPropertyChanged("paytypeDetail");
					this.OnpaytypeDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Int")]
		public System.Nullable<int> discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				if ((this._discount != value))
				{
					this.OndiscountChanging(value);
					this.SendPropertyChanging();
					this._discount = value;
					this.SendPropertyChanged("discount");
					this.OndiscountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.savingAmount")]
	public partial class savingAmount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _savCode;
		
		private System.Nullable<int> _savAmt;
		
		private System.Nullable<int> _reward;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsavCodeChanging(string value);
    partial void OnsavCodeChanged();
    partial void OnsavAmtChanging(System.Nullable<int> value);
    partial void OnsavAmtChanged();
    partial void OnrewardChanging(System.Nullable<int> value);
    partial void OnrewardChanged();
    #endregion
		
		public savingAmount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savCode", DbType="NVarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string savCode
		{
			get
			{
				return this._savCode;
			}
			set
			{
				if ((this._savCode != value))
				{
					this.OnsavCodeChanging(value);
					this.SendPropertyChanging();
					this._savCode = value;
					this.SendPropertyChanged("savCode");
					this.OnsavCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savAmt", DbType="Int")]
		public System.Nullable<int> savAmt
		{
			get
			{
				return this._savAmt;
			}
			set
			{
				if ((this._savAmt != value))
				{
					this.OnsavAmtChanging(value);
					this.SendPropertyChanging();
					this._savAmt = value;
					this.SendPropertyChanged("savAmt");
					this.OnsavAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reward", DbType="Int")]
		public System.Nullable<int> reward
		{
			get
			{
				return this._reward;
			}
			set
			{
				if ((this._reward != value))
				{
					this.OnrewardChanging(value);
					this.SendPropertyChanging();
					this._reward = value;
					this.SendPropertyChanged("reward");
					this.OnrewardChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.benefitType")]
	public partial class benefitType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _benefitCode;
		
		private string _benefitDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbenefitCodeChanging(string value);
    partial void OnbenefitCodeChanged();
    partial void OnbenefitDetailChanging(string value);
    partial void OnbenefitDetailChanged();
    #endregion
		
		public benefitType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_benefitCode", DbType="NVarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string benefitCode
		{
			get
			{
				return this._benefitCode;
			}
			set
			{
				if ((this._benefitCode != value))
				{
					this.OnbenefitCodeChanging(value);
					this.SendPropertyChanging();
					this._benefitCode = value;
					this.SendPropertyChanged("benefitCode");
					this.OnbenefitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_benefitDetail", DbType="NVarChar(100)")]
		public string benefitDetail
		{
			get
			{
				return this._benefitDetail;
			}
			set
			{
				if ((this._benefitDetail != value))
				{
					this.OnbenefitDetailChanging(value);
					this.SendPropertyChanging();
					this._benefitDetail = value;
					this.SendPropertyChanged("benefitDetail");
					this.OnbenefitDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paidUp")]
	public partial class paidUp
	{
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _paidAmt;
		
		private string _year;
		
		private string _gender;
		
		public paidUp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paidAmt", DbType="Int")]
		public System.Nullable<int> paidAmt
		{
			get
			{
				return this._paidAmt;
			}
			set
			{
				if ((this._paidAmt != value))
				{
					this._paidAmt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="NVarChar(4)")]
		public string year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this._year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(2)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.surrender")]
	public partial class surrender
	{
		
		private System.Nullable<int> _age;
		
		private string _year;
		
		private System.Nullable<int> _surAmt;
		
		private string _gender;
		
		public surrender()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="NVarChar(4)")]
		public string year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this._year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surAmt", DbType="Int")]
		public System.Nullable<int> surAmt
		{
			get
			{
				return this._surAmt;
			}
			set
			{
				if ((this._surAmt != value))
				{
					this._surAmt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(2)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fundAmt")]
	public partial class fundAmt
	{
		
		private string _gender;
		
		private System.Nullable<int> _age;
		
		private string _benefitCode;
		
		private System.Nullable<int> _savAmt;
		
		private System.Nullable<int> _fundAmt1;
		
		private System.Nullable<int> _reward;
		
		private System.Nullable<int> _netMonth;
		
		private System.Nullable<int> _netQuarter;
		
		private System.Nullable<int> _discountSemiAnnual;
		
		private System.Nullable<int> _netSemiAnnual;
		
		private System.Nullable<int> _discountAnnual;
		
		private System.Nullable<int> _netAnnual;
		
		public fundAmt()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(2)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_benefitCode", DbType="NVarChar(2)")]
		public string benefitCode
		{
			get
			{
				return this._benefitCode;
			}
			set
			{
				if ((this._benefitCode != value))
				{
					this._benefitCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savAmt", DbType="Int")]
		public System.Nullable<int> savAmt
		{
			get
			{
				return this._savAmt;
			}
			set
			{
				if ((this._savAmt != value))
				{
					this._savAmt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="fundAmt", Storage="_fundAmt1", DbType="Int")]
		public System.Nullable<int> fundAmt1
		{
			get
			{
				return this._fundAmt1;
			}
			set
			{
				if ((this._fundAmt1 != value))
				{
					this._fundAmt1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reward", DbType="Int")]
		public System.Nullable<int> reward
		{
			get
			{
				return this._reward;
			}
			set
			{
				if ((this._reward != value))
				{
					this._reward = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_netMonth", DbType="Int")]
		public System.Nullable<int> netMonth
		{
			get
			{
				return this._netMonth;
			}
			set
			{
				if ((this._netMonth != value))
				{
					this._netMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_netQuarter", DbType="Int")]
		public System.Nullable<int> netQuarter
		{
			get
			{
				return this._netQuarter;
			}
			set
			{
				if ((this._netQuarter != value))
				{
					this._netQuarter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountSemiAnnual", DbType="Int")]
		public System.Nullable<int> discountSemiAnnual
		{
			get
			{
				return this._discountSemiAnnual;
			}
			set
			{
				if ((this._discountSemiAnnual != value))
				{
					this._discountSemiAnnual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_netSemiAnnual", DbType="Int")]
		public System.Nullable<int> netSemiAnnual
		{
			get
			{
				return this._netSemiAnnual;
			}
			set
			{
				if ((this._netSemiAnnual != value))
				{
					this._netSemiAnnual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountAnnual", DbType="Int")]
		public System.Nullable<int> discountAnnual
		{
			get
			{
				return this._discountAnnual;
			}
			set
			{
				if ((this._discountAnnual != value))
				{
					this._discountAnnual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_netAnnual", DbType="Int")]
		public System.Nullable<int> netAnnual
		{
			get
			{
				return this._netAnnual;
			}
			set
			{
				if ((this._netAnnual != value))
				{
					this._netAnnual = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Class1
	{
		
		private string _Property1;
		
		public Class1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property1", CanBeNull=false)]
		public string Property1
		{
			get
			{
				return this._Property1;
			}
			set
			{
				if ((this._Property1 != value))
				{
					this._Property1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
