<?xml version="1.0" encoding="utf-8"?><Database Name="BAACLIFECAL" Class="dbAccountDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=alldev;Initial Catalog=BAACLIFECAL;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BAACLIFECALConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.gender" Member="genders">
    <Type Name="gender">
      <Column Name="genderCode" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="genderDetail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.paytype" Member="paytypes">
    <Type Name="paytype">
      <Column Name="paytypeCode" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="paytypeDetail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.savingAmount" Member="savingAmounts">
    <Type Name="savingAmount">
      <Column Name="savCode" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="savAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reward" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.benefitType" Member="benefitTypes">
    <Type Name="benefitType">
      <Column Name="benefitCode" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="benefitDetail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.paidUp" Member="paidUps">
    <Type Name="paidUp">
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="paidAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="year" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.surrender" Member="surrenders">
    <Type Name="surrender">
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="year" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="surAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.fundAmt" Member="fundAmts">
    <Type Name="fundAmt">
      <Column Name="gender" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="benefitCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="savAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fundAmt" Member="fundAmt1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reward" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="netMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="netQuarter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="discountSemiAnnual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="netSemiAnnual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="discountAnnual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="netAnnual" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>